- name: Setup and run signal tasks
  hosts: SIGNAL_NODE
  become: yes
  vars:
    simul_dir: /home/dcog/simul
    docker_image: deryacog/flsignal:latest
    container_name: flsignal
  tasks:
    - name: Pull flsignal Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run flsignal container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        detach: true
        ports:
          - "8765:8765"
        log_driver: "json-file"
        log_options:
          max-size: "10m"
          max-file: "4"

    - name: Wait for 10 seconds to ensure flsignal is running
      pause:
        seconds: 10

- name: Setup and run fledger tasks
  hosts: FLEDGER_NODES
  become: yes
  vars:
    path_len: 3
    retry: 2
    simul_dir: /home/dcog/simul
    docker_image: deryacog/fledger:latest
  tasks:
    - name: Pull fledger Docker image
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Create simul directory on fledger nodes
      file:
        path: "{{ simul_dir }}"
        state: directory
        mode: '0755'

    - name: Copy loopix core config file
      copy:
        src: /home/dcog/loopix_core_config.yaml
        dest: /home/dcog/loopix_core_config.yaml

    - name: Run fledger containers
      docker_container:
        name: "fledger_{{ inventory_hostname }}"
        image: "{{ docker_image }}"
        state: started
        detach: true
        volumes:
          - "{{ simul_dir }}:/config"
          - "{{ simul_dir }}/loopix_core_config.yaml:/fledger/loopix_core_config.yaml"
        command: >
          --config /config
          --name {{ inventory_hostname }}
          -vv
          -s ws://{{ groups['SIGNAL_NODE'][0] }}:8765
          {% if inventory_hostname == 'node-1' %}--path-len {{ path_len }}{% endif %}
          {% if retry > 0 %}--retry {{ retry }}{% endif %}
        log_driver: "json-file"
        log_options:
          max-size: "10m"
          max-file: "4"

    - name: Wait for 60 seconds
      pause:
        seconds: 60

- name: Cleanup signal processes
  hosts: SIGNAL_NODE
  become: yes
  tasks:
    - name: Stop flsignal container
      shell: docker stop flsignal || true
      ignore_errors: true

- name: Cleanup fledger processes
  hosts: FLEDGER_NODES
  become: yes
  tasks:
    - name: Stop fledger container
      shell: docker stop fledger_{{ inventory_hostname }} || true
      ignore_errors: true